[pytest]
# -v                              : подробный вывод (видно каждый тест)
# --screenshot=only-on-failure    : Playwright сам сохраняет скриншот ТОЛЬКО при падении
# --output=test-results           : куда складывать эти скриншоты
# --browser chromium              : в каком браузере гонять UI-тесты
addopts = -v --screenshot=only-on-failure --output=test-results --browser chromium
